name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add permissions for security scanning
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Set the node version to 20

      - name: Install dependencies
        run: npm ci # Install dependencies for the project

      - name: Run linting
        run: npm run lint # Add linting rules to check for errors and warnings of the code

      - name: Build application
        run: npm run build # Build the application

      - name: Security scan
        run: npm audit # Run security scan to check for vulnerabilities in the code

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          scanners: "vuln,secret"
          severity: "CRITICAL,HIGH,MEDIUM"

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
